name: Run Shell Script on Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install libudev-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
      - name: Run Shell Script
        run: |
          # Your shell script commands here
          ./build_and_run.sh
          
      - name: Validate Script
        run: |
          if [ $? -eq 0 ]; then
            echo "Script executed successfully"
          else
            echo "Script execution failed"
            exit 1
          fi
